const QuestionsDb = [
    {
        question: "Right now I'm feeling...",
        selectOne: false,
        options: [
            "Overwhelmed/Confused",
            "Sad/Lonely",
            "Existential",
            "Peaceful/Happy",
            "Angry",
            "Hopeful/Determined",
            "Praying",
            "Discouraged/Lethargic"
        ]
    },
    {
        question: "My default to unwind is...",
        selectOne: false,
        options: [
            "A Show",
            "A Movie",
            "A Book",
            "Going Out",
            "Chill with Friends",
            "Outdoor Adventures",
            "Hobby"
        ]
    },
    {
        question: "I think my role in making the world a better place has something to do with...",
        selectOne: false,
        options: [
            "Art/Writing/Film Making/Music etc.",
            "Activism/Politics",
            "Health Care/Counseling",
            "Teacher",
            "Family/Relationships",
            "First Responder/Military"
        ]
    },
    {
        question: "Some of my favorite fictional characters are...",
        selectOne: false,
        options: [
            "Jim Halpert",
            "Pam Halpert",
            "Michael Scott",
            "Dwight Schrutte",
            "Leslie Knope",
            "Ben Wyatt",
            "Ron Swanson",
            "Eleanor Shellstrop",
            "Chidi Anagonye",
            "Tahani Al-Jamil",
            "Jason Mendoza",
            "Frodo Baggins",
            "Sam Gamgee",
            "Merry Brandybuck",
            "Pippin Took",
            "Aragorn",
            "Boromir",
            "Gandalf",
            "Legolas",
            "Gimli",
            "Eowyn",
            "Edmund Pevensie",
            "Lucy Pevensie",
            "Harry Potter",
            "Hermione Granger",
            "Ron Weasley",
            "Fred and George Weasley",
            "Dumbledore",
            "Sirius Black",
            "Remus Lupin",
            "Elizabeth Bennet",
            "Jane Bennet",
            "Mr. Bingley",
            "Mr. Darcy",
            "Lorelai Gilmore",
            "Rory Gilmore",
            "Jack Pearson",
            "Rebecca Pearson",
            "Kevin Pearson",
            "Kate Pearson",
            "Randall Pearson",
            "Buzz Lightyear",
            "Woody",
            "Walter Mitty",
            "Captain America",
            "Iron Man",
            "Black Widow",
            "Thor",
            "Hawkeye",
            "Hulk",
            "Loki",
            "Black Panther",
            "Spider Man",
            "Chuck Bartowski",
            "Sarah Walker",
            "John Casey",
            "Meg March",
            "Jo March",
            "Beth March",
            "Amy March",
            "Laurie",
            "Dmitry Karamazov",
            "Ivan Karamazov",
            "Alyosha Karamazov"
        ]
    },
    {
        question: "My personality type is...",
        selectOne: true,
        options: [
            "Not sure",
            "Don't know, don't care",
            "Please don't",
            "ESFJ",
            "ESFP",
            "ISFJ",
            "ISFP",
            "ENFJ",
            "ENFP",
            "INFJ",
            "INFP",
            "ESTJ",
            "ESTP",
            "ISTJ",
            "ISTP",
            "ENTJ",
            "ENTP",
            "INTJ",
            "INTP"
        ]
    },
    {
        question: "What I need in my life right now is...",
        selectOne: false,
        options: [
            "Perspective",
            "Encouragement",
            "Motivation",
            "Empowerment",
            "Humor",
            "A Deep Breath"
        ]
    }
]

export default QuestionsDb;